name = "vanutils"
main = "./dist/_worker.js/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
exclude = ["_worker.js/**", "_worker.js"]

[build]
command = "npm run build"
