import type { ToolMeta, VancouverLocationPreset } from '../types/shared';

export const TOOLS_REGISTRY: ToolMeta[] = [
  // --- ROW 1: CRITICAL DAILY VITALS & TRANSIT ---
  {
    id: 'weather-forecast',
    name: 'Microclimate Weather Radar',
    shortDescription: 'Real-time hyper-local temperatures, 24h precipitation curves, wind & UV across Metro Vancouver microclimates.',
    path: '/weather',
    icon: 'sun',
    category: 'outdoors',
    status: 'active',
    badgeText: 'Microclimate Radar',
    previewStat: {
      value: '19.4°C',
      label: 'Downtown • 0mm Rain',
      statusType: 'safe',
    },
    features: [
      'Coastal vs. North Shore microclimate soundings',
      '24-Hour hourly rain accumulation sparklines',
      'Environment Canada active weather alert ribbon',
      '1-Tap GPS closest neighborhood station locator',
    ],
  },
  {
    id: 'bridge-traffic',
    name: 'Bridges & Tunnel Radar',
    shortDescription: 'Live crossing delays, dynamic counterflow lane directions (Lions Gate, Massey, Alex Fraser) & DriveBC webcams.',
    path: '/bridges',
    icon: 'compass',
    category: 'transit',
    status: 'active',
    badgeText: 'Live Crossings',
    previewStat: {
      value: '2 Lanes NB',
      label: 'Lions Gate Counterflow',
      statusType: 'info',
    },
    features: [
      'Live crossing delays vs. baseline normal',
      'Dynamic counterflow lane signal visualizer',
      'Synchronized DriveBC approach webcams',
      'DriveBC Open511 active incident radar',
    ],
  },
  {
    id: 'bc-ferries',
    name: 'Ferry Standby Radar',
    shortDescription: 'Real-time deck capacity, sailing wait times & standby odds for Tsawwassen & Horseshoe Bay.',
    path: '/ferries',
    icon: 'ship',
    category: 'transit',
    status: 'active',
    badgeText: 'Live Marine Radar',
    previewStat: {
      value: 'Live Deck Space',
      label: 'Standby deck space',
      statusType: 'safe',
    },
    features: [
      'Real-time vehicle deck percentage',
      'Standby clearance risk indicators',
      'Hullo fast catamaran schedules',
      'DriveBC approach highway webcams',
    ],
  },
  {
    id: 'health-wait-times',
    name: 'ER & Urgent Care Radar',
    shortDescription: 'Real-time hospital emergency department wait times, triage estimates & UPCC same-day walk-in clinic capacity.',
    path: '/health',
    icon: 'activity',
    category: 'daily_living',
    status: 'active',
    badgeText: 'Live Wait Times',
    previewStat: {
      value: '1h 15m Shortest',
      label: 'Mt. Saint Joseph ER',
      statusType: 'safe',
    },
    features: [
      'Real-time estimated time to physician',
      'Total Time to Care (Drive + Wait) calculator',
      'Clinical ER vs. UPCC triage selector',
      '11 Hospital ERs & 9 Urgent Care Centres',
    ],
  },

  // --- ROW 2: MOBILITY & ENVIRONMENTAL HEALTH ---
  {
    id: 'evo-parking',
    name: 'Car-Share Safe Parking',
    shortDescription: 'Instant 3-second parking clearance for Evo/Modo, street sweeping schedules, rush lane tow alerts & YVR/UBC lots.',
    path: '/parking',
    icon: 'car',
    category: 'daily_living',
    status: 'active',
    badgeText: 'Live Parking Radar',
    previewStat: {
      value: 'Home Zone OK',
      label: 'Safe to Park Today',
      statusType: 'safe',
    },
    features: [
      '1-Tap GPS spot safety evaluation',
      'Street sweeping & leaf cleaning countdown',
      'Peak-hour rush lane no-stopping radar',
      'Dedicated YVR Airport & UBC parkades guide',
    ],
  },
  {
    id: 'air-quality',
    name: 'Wildfire Smoke & AQHI',
    shortDescription: 'Real-time Air Quality Health Index (AQHI), PM2.5 particulate levels from BAM-1020 sensors & clean-air shelters.',
    path: '/air',
    icon: 'wind',
    category: 'outdoors',
    status: 'active',
    badgeText: 'Live Smoke Radar',
    previewStat: {
      value: 'AQHI 2',
      label: 'Low Health Risk',
      statusType: 'safe',
    },
    features: [
      'BAM-1020 fine particulate (PM2.5) sensors',
      '24-hour smoke trajectory sparklines',
      'Air-conditioned clean-air shelter directory',
      'Metro Vancouver wildfire smoke alerts',
    ],
  },
  {
    id: 'mountain-snow',
    name: 'Mountain Snow Line',
    shortDescription: 'North Shore freezing levels, Cypress/Seymour/Grouse status & synchronized summit webcams.',
    path: '/snow',
    icon: 'mountain-snow',
    category: 'outdoors',
    status: 'active',
    badgeText: 'Live Snow Radar',
    previewStat: {
      value: '3,900m FZ (Summer)',
      label: 'Freezing level today',
      statusType: 'safe',
    },
    features: [
      'Elevation freezing line tracker',
      'Unified mountain webcams matrix',
      'Tire chain requirement radar',
      '12h/24h snow stake accumulations',
    ],
  },
  {
    id: 'can-i-swim',
    name: 'Can I Swim?',
    shortDescription: 'Real-time Metro Vancouver beach water quality, E. coli readings & safety advisories.',
    path: '/swim',
    icon: 'waves',
    category: 'outdoors',
    status: 'active',
    badgeText: 'Summer Favorite',
    previewStat: {
      value: '31 Beaches',
      label: 'Monitored Sites',
      statusType: 'safe',
    },
    features: [
      'Traffic light safety badges',
      '30-day E. coli geometric trends',
      'Dog-friendly & lifeguard filters',
      'Nearest clean beach sorting',
    ],
  },

  // --- ROW 3: CITY PULSE, SPORTS & REAL ESTATE ---
  {
    id: 'local-news',
    name: 'Local News & Alerts',
    shortDescription: 'Sub-second, zero-ad civic news wire, breaking weather warnings, transit updates & City Council releases.',
    path: '/news',
    icon: 'newspaper',
    category: 'civic',
    status: 'active',
    badgeText: 'Live Wire',
    previewStat: {
      value: 'Live Wire',
      label: 'CBC • City • ECCC',
      statusType: 'info',
    },
    features: [
      'Breaking weather & transit alert ribbon',
      'Verified non-paywalled local journalism',
      'Sub-second keyword & category filtering',
      'Direct citations to primary public sources',
    ],
  },
  {
    id: 'sports-teams',
    name: 'Major Sports Teams Radar',
    shortDescription: 'Live scores, game day schedules, 5-game form & TV/radio broadcast channels for Canucks, Whitecaps, BC Lions & Canadians.',
    path: '/sports-teams',
    icon: 'trophy',
    category: 'outdoors',
    status: 'active',
    badgeText: 'Live Game Radar',
    previewStat: {
      value: 'Canucks vs CGY',
      label: 'Next Game • 7:00 PM',
      statusType: 'safe',
    },
    features: [
      'Real-time scores & period/quarter tracking',
      'Visual 5-game form streak indicators (W/L/OTL)',
      'Direct TV & Radio broadcast channel listings',
      'Rogers Arena & BC Place SkyTrain transit wayfinding',
    ],
  },
  {
    id: 'housing-market',
    name: 'Real Estate & Rental Pulse',
    shortDescription: 'Sub-50ms market liquidity telemetry, MLS® HPI benchmark prices, rental vacancy rates & BoC mortgage rates.',
    path: '/market',
    icon: 'home',
    category: 'daily_living',
    status: 'active',
    badgeText: 'MLS® & Rental Pulse',
    previewStat: {
      value: '18.4% SAR',
      label: 'Balanced Market',
      statusType: 'safe',
    },
    features: [
      'Sales-to-Active Ratio (SAR %) liquidity gauge',
      'MLS® HPI Condo, Townhouse & Detached indices',
      'CMHC median rental prices & vacancy rates',
      'Bank of Canada policy rate & payment calculator',
    ],
  },
  {
    id: 'sports-courts',
    name: 'Sports, Courts & Rec Radar',
    shortDescription: 'Sub-second recreation radar for public tennis courts, lighted pickleball, length swimming & ice rinks.',
    path: '/sports',
    icon: 'sparkles',
    category: 'outdoors',
    status: 'active',
    badgeText: 'Park Board Rec',
    previewStat: {
      value: '84 Courts',
      label: 'Lighted & Open',
      statusType: 'safe',
    },
    features: [
      'Tennis & lighted pickleball night curfew locator',
      'Live length swim & public pool session schedules',
      'Ice rink public skate & drop-in hockey hours',
      'Turf athletic field rainout & floodlight status',
    ],
  },

  // --- ROW 4: COMMUNITY & CIVIC ---
  {
    id: 'community-events',
    name: 'Free & Local Events',
    shortDescription: '100% free, all-ages, and family-friendly local street festivals, outdoor movies, and community events.',
    path: '/events',
    icon: 'calendar',
    category: 'daily_living',
    status: 'active',
    badgeText: '100% Free Events',
    previewStat: {
      value: '6 Free',
      label: 'This Weekend',
      statusType: 'safe',
    },
    features: [
      'Strict non-commercial / zero-ad filter',
      'Chronological date selector',
      '1-tap .ics calendar download & maps',
      'SkyTrain and bus transit routing notes',
    ],
  },
  {
    id: 'school-catchment',
    name: 'School Catchment & Childcare',
    shortDescription: 'Sub-50ms lookup for VSB SD39 Elementary, Annex & High School catchments, French Immersion & licensed daycares.',
    path: '/schools',
    icon: 'academic',
    category: 'civic',
    status: 'active',
    badgeText: 'VSB SD39',
    previewStat: {
      value: '18 Catchments',
      label: 'Vancouver SD39',
      statusType: 'info',
    },
    features: [
      'Elementary, Annex & Secondary lookup',
      'Early & Late French Immersion feeder tracks',
      'Licensed daycares with VCH compliance records',
      'Direct link to official VSB student registration',
    ],
  },
  {
    id: 'civic-development',
    name: 'Development & Rezoning',
    shortDescription: 'Proposed towers, Broadway Plan rezonings, below-market social housing & City Council public hearing alerts.',
    path: '/civic',
    icon: 'building',
    category: 'civic',
    status: 'active',
    badgeText: 'Active Proposals',
    previewStat: {
      value: '38 Towers',
      label: 'Broadway Plan Corridor',
      statusType: 'info',
    },
    features: [
      'Spatial proximity radius (250m–2000m)',
      'Storeys, FSR & unit mix breakdown',
      'Council public hearing countdown & comments',
      'Architectural elevation drawing deep-links',
    ],
  },
];

export const VANCOUVER_LOCATION_PRESETS: VancouverLocationPreset[] = [
  {
    id: 'downtown',
    name: 'Downtown Vancouver',
    neighborhood: 'Granville / Robson',
    coords: { latitude: 49.2827, longitude: -123.1207 },
  },
  {
    id: 'west-end',
    name: 'West End',
    neighborhood: 'Denman / Davie',
    coords: { latitude: 49.2861, longitude: -123.1362 },
  },
  {
    id: 'kitsilano',
    name: 'Kitsilano',
    neighborhood: 'West 4th / Yew',
    coords: { latitude: 49.2684, longitude: -123.1558 },
  },
  {
    id: 'mount-pleasant',
    name: 'Mount Pleasant',
    neighborhood: 'Main & Broadway',
    coords: { latitude: 49.2632, longitude: -123.1009 },
  },
  {
    id: 'commercial-drive',
    name: 'Commercial Drive',
    neighborhood: 'Grandview-Woodland',
    coords: { latitude: 49.2738, longitude: -123.0694 },
  },
  {
    id: 'north-van-lonsdale',
    name: 'North Vancouver',
    neighborhood: 'Lower Lonsdale / Shipyards',
    coords: { latitude: 49.3134, longitude: -123.0789 },
  },
  {
    id: 'west-van-ambleside',
    name: 'West Vancouver',
    neighborhood: 'Ambleside Park',
    coords: { latitude: 49.3275, longitude: -123.1582 },
  },
  {
    id: 'burnaby-metrotown',
    name: 'Burnaby',
    neighborhood: 'Metrotown / Central Park',
    coords: { latitude: 49.2276, longitude: -123.0076 },
  },
  {
    id: 'richmond-centre',
    name: 'Richmond',
    neighborhood: 'Minoru / City Centre',
    coords: { latitude: 49.1666, longitude: -123.1336 },
  },
  {
    id: 'white-rock-pier',
    name: 'White Rock',
    neighborhood: 'Marine Drive / Pier',
    coords: { latitude: 49.0205, longitude: -122.8028 },
  },
];
